# Generated by Django 3.0.6 on 2020-05-13 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='Dan W.', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
