# Generated by Django 3.0.6 on 2020-05-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='list_date',
            new_name='date',
        ),
    ]
